### ISSUE TITLE
Secure HTTP Responses to prevent too application dates

### ISSUE THREAD

**Issue by dankkomcg** [dankkomcg/hyttp#1]
## Task

* [ ] Use `header_remove` to prevent use HTTP headers: `Power-By`, `Server`...
* [ ] Use header_register_callback
* [ ] Make this like optional work when a `HyTTPResponse` is called (pass a boolean option on params).

## Example

```
function foo() {
 foreach (headers_list() as $header) {
   if (strpos($header, 'X-Powered-By:') !== false) {
     header_remove('X-Powered-By');
   }
   header_remove('X-Test');
 }
}

$result = header_register_callback('foo');
```
